### ISSUE TITLE
Please fix the floating image problem

### ISSUE THREAD

**Issue by vikasz1** [Varanasi-Coders/Biet-Bubble#4]
It is present in the main activity of the page.

**Comment by vikasz1** [comment]
Please use my attached file instead of yours.
![image](https://user-images.githubusercontent.com/62638545/136610713-3b200353-6570-42a8-857e-9322c17a68c5.png)

**Comment by alkaz1** [comment]
Please replace your activity_main.xml by my attached file.
![image](https://user-images.githubusercontent.com/91754656/136610850-73b5dddf-4240-462a-9ad7-fc534641ddf2.png)

**Comment by vikasz1** [comment]
Thank you
